#!/bin/bash
COMMIT_MSG_FILE=$1

echo "Checking code quality..."
cargo test --quiet
RESULT=$?

if [ $RESULT -eq 0 ]; then
    STATUS="[P]"
else
    STATUS="[F]"
fi

sed -i "" "1s/$/ $STATUS/" "$COMMIT_MSG_FILE"
