all: fmt bsp build

fmt:
	scalafmt ./src/

bsp:
	mill --bsp-install

build:
	mill nativeLink
	cp out/nativeLink.dest/out ./sonnetc

run file:
	./sonnetc {{ file }} --verbose

	@DIR=$(dirname "{{ file }}"); \
	BASE=$(basename "{{ file }}" | cut -f 1 -d '.'); \
	qbe "$DIR/build/$BASE.qbe" > "$DIR/build/$BASE.s"

	@DIR=$(dirname "{{ file }}"); \
	BASE=$(basename "{{ file }}" | cut -f 1 -d '.'); \
	gcc -Wall -Wextra -Wpedantic -Werror \
		"$DIR/build/$BASE.s" \
		stdlib/*.c \
		-o "$DIR/build/$BASE"

	# Runtime Output:
	@DIR=$(dirname "{{ file }}"); \
	BASE=$(basename "{{ file }}" | cut -f 1 -d '.'); \
	"$DIR/build/$BASE"