/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.5.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
	// Apply the application plugin to add support for building a CLI application in Java.
	application
	id("com.diffplug.spotless") version "8.4.0"
}

configure<com.diffplug.gradle.spotless.SpotlessExtension> {
	java {
		// format the code as saruman wants
		palantirJavaFormat()

		leadingSpacesToTabs()

		removeUnusedImports()
		trimTrailingWhitespace()
		endWithNewline()
	}
}


repositories {
	// Use Maven Central for resolving dependencies.
	mavenCentral()
}

dependencies {
	// Use JUnit test framework.
	testImplementation(libs.junit)

	// This dependency is used by the application.
	implementation(libs.guava)

}

// Apply a specific Java toolchain to ease working on different environments.
java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

application {
	// Define the main class for the application.
	mainClass = "org.example.App"
}

tasks.named<JavaExec>("run") {
	workingDir = rootProject.projectDir
	standardInput = System.`in`
}